// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7f_3YPpUQ_fNcDe3Qwd9ypJw1zKmVB0',
    appId: '1:794361179548:web:00060a5eb0e5290a156c59',
    messagingSenderId: '794361179548',
    projectId: 'push-notification-e4513',
    authDomain: 'push-notification-e4513.firebaseapp.com',
    storageBucket: 'push-notification-e4513.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEFUsCVXA21We2ytuzAOMXdi9oy6Nagb4',
    appId: '1:794361179548:android:ef89f364a1200108156c59',
    messagingSenderId: '794361179548',
    projectId: 'push-notification-e4513',
    storageBucket: 'push-notification-e4513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi_O8z1hyzUUbROShVyU45aBNqtUWhV9o',
    appId: '1:794361179548:ios:49466355da5e3897156c59',
    messagingSenderId: '794361179548',
    projectId: 'push-notification-e4513',
    storageBucket: 'push-notification-e4513.appspot.com',
    iosBundleId: 'com.example.gulahmedshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi_O8z1hyzUUbROShVyU45aBNqtUWhV9o',
    appId: '1:794361179548:ios:152766c9f7bcbc13156c59',
    messagingSenderId: '794361179548',
    projectId: 'push-notification-e4513',
    storageBucket: 'push-notification-e4513.appspot.com',
    iosBundleId: 'com.example.gulahmedshop.RunnerTests',
  );
}
